### ISSUE TITLE
icozip  make error

### ISSUE THREAD

**Issue by oystercatcher** [ZipCPU/icozip#2]
fedora 30     /usr/local/src   for default directory
yosys, arachne-pnr, icestorm   from   repositories  

 
yosys -V
Yosys 0.8 (git sha1 UNKNOWN, gcc 9.0.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os)

git clone autofpga     and make
autofpga -V
autofpga
built on 20190830

I have copied   board.ld   and icozip.pcf   to auto-fpga directory 
then run make which errors after some time

yosys -ql yosys.log -p synth_ice40 -blif icozip.blif -top toplevel ...
toplevel.v:184: ERROR: Identifier `\i_clk' is implicitly declared and `default_nettype is set to none.

**Comment by ZipCPU** [comment]
Looks like a clock upgrade to autofpga didn't make it to IcoZip.  AutoFPGA now supports a CLOCK.TOP key to specify the name of a top-level clock.

I've also got plenty of updates to the project, so let me push some updates to fix this.

**Comment by oystercatcher** [comment]
Thank you Sir,  I am just a hobbyist so I will continue learning from yourvery educational website.







    On Monday, September 2, 2019, 5:41:20 PM PDT, Dan Gisselquist <notifications@github.com> wrote:  
 
 
Looks like a clock upgrade to autofpga didn't make it to IcoZip. AutoFPGA now supports a CLOCK.TOP key to specify the name of a top-level clock.

I've also got plenty of updates to the project, so let me push some updates to fix this.

**Comment by ZipCPU** [comment]
The repo has been updated with a lot of changes.  I've verified it with both the CPU test and the hello world--both running from simulation.

Try it again, and see if you can get it to work,

Dan
