### ISSUE TITLE
fedora 31  error with arachne-pnr

### ISSUE THREAD

**Issue by oystercatcher** [ZipCPU/icozip#3]
I have been testing icozip  with  fedora 31  , fedora 30 and rpi buster.
This error appears on fedora 31 but not fedora 30.     
Not sure if this has anything to do with icozip but asking for advice.

2.46. Executing BLIF backend.

End of script. Logfile hash: f057ca0d26
CPU: user 0.66s system 0.02s, MEM: 50.52 MB total, 44.84 MB resident
Yosys 0.9 (git sha1 UNKNOWN, gcc 9.1.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os)
Time spent: 52% 10x read_verilog (0 sec), 14% 1x share (0 sec), ...
arachne-pnr -d 8k -r -P ct256 -p blinky.pcf -o blinky.asc blinky.blif
seed: 2281212662
device: 8k
read_chipdb +/share/arachne-pnr/chipdb-8k.bin...
  supported packages: bg121, bg121:4k, cb132, cb132:4k, cm121, cm121:4k, cm225, cm225:4k, cm81, cm81:4k, ct256, tq144:4k
read_blif blinky.blif...
prune...
read_pcf blinky.pcf...
instantiate_io...
pack...

After packing:
IOs          6 / 206
GBs          0 / 8
  GB_IOs     0 / 8
LCs          32 / 7680
  DFF        3
  CARRY      2
  CARRY, DFF 24
  DFF PASS   0
  CARRY PASS 1
BRAMs        0 / 32
WARMBOOTs    0 / 1
PLLs         0 / 2

place_constraints...
promote_globals...
  promoted i_clk$2, 27 / 27
  promoted 1 nets
    1 clk
  1 globals
    1 clk
realize_constants...
place...
  initial wire length = 355
  at iteration #50: temp = 12.9827, wire length = 192
  at iteration #100: temp = 5.42833, wire length = 132
  at iteration #150: temp = 1.43048, wire length = 106
  final wire length = 99

After placement:
PIOs       5 / 206
PLBs       8 / 960
BRAMs      0 / 32

  place time 0.06s
route...
/usr/include/c++/9/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = std::pair<int, int>; _Alloc = std::allocator<std::pair<int, int> >; std::vector<_Tp, _Alloc>::reference = std::pair<int, int>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
make[2]: *** [Makefile:48: blinky.asc] Aborted (core dumped)
rm blinky.blif
make[1]: *** [Makefile:47: basic] Error 2
make: *** [Makefile:158: rtl] Error 2
[pstan@daidokoro-ci-org icozip]$

**Comment by ZipCPU** [comment]
The design should build with nextpnr, not arachnepnr.  arachnepnr is no longer maintained, whereas nextpnr gets better performance.  The fact that the makefile's are still using arachnepnr is a bug that needs to be fixed.

**Comment by oystercatcher** [comment]
ok   thanks.
I didn't have  nextpnr on the system when I ran make, so that explains the problem.    
Fedora doesn't package  nextpnr  quite yet.I have been trying to build zipcpu  using just theprebuilt packages  as it will be much easier todocument the process for other users.
I will give  nextpnr  from git a try.
    On Wednesday, November 27, 2019, 7:05:40 PM PST, Dan Gisselquist <notifications@github.com> wrote:  
 
 
The design should build with nextpnr, not arachnepnr. arachnepnr is no longer maintained, whereas nextpnr gets better performance. The fact that the makefile's are still using arachnepnr is a bug that needs to be fixed.

**Comment by ZipCPU** [comment]
This was fixed in [8b7a4a65](https://github.com/ZipCPU/icozip/commit/8b7a4a65fead84e7ae315b4a97a23b357e6bca7c), and should've been closed long ago.

Dan
