### ISSUE TITLE
iCE40HX8K-EVB olimex

### ISSUE THREAD

**Issue by danielitzahi** [ZipCPU/icozip#4]
Hi 
Very nice web site Zipcpu
Very nice work
Can i generate project with AutoFpga
For this board iCE40HX8K-EVB olimex
It is very similar to icoboard
Best regard

**Comment by ZipCPU** [comment]
> Very nice web site Zipcpu
> Very nice work

Thank you!

> Can i generate project with AutoFpga

Absolutely!

> For this board iCE40HX8K-EVB olimex
> It is very similar to icoboard

I have no background with the olimex board.  Expect to need to make changes, but nothing is stopping you.  Go for it!

Dan
